# -*- coding: utf-8 -*-
"""Seasonal-Agriculture-Performance-Analysis-Major-Data Analytics-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alu8mQ4nHN2yz3AOD_WEo92wCFH0txyH

Seasonal Agriculture Performance Analysis
Major Data Analytics Project

Domain: Agriculture

Project Theme: Seasonal Agriculture Performance

Tools: Python, Pandas, NumPy, Matplotlib, Seaborn

Project Goal

Investigate how agricultural performance varies across seasons and identify meaningful patterns, trends, relationships and differences in the available data.

**Problem Statement**
Agricultural activities are influenced by seasonal variations in environmental conditions,
farming practices, resource availability and market conditions. As a result, agricultural
performance may differ from one season to another.
However, raw agricultural data does not clearly explain how agricultural performance changes
across seasons or what patterns can be observed in different seasonal conditions.
The problem is to analyze the given agricultural dataset and investigate seasonal differences
in agricultural performance by identifying meaningful patterns, trends, relationships and
variations within the available data.

**OBJECTIVE:**

The primary objective of this project is to analyze agricultural data from different seasons
and identify meaningful patterns, trends, relationships and differences in agricultural
performance.
Students should independently:
 Explore and understand the dataset.
 Clean and prepare the data for analysis.
 Examine how agricultural performance varies across seasons.
 Identify important seasonal patterns and trends.
 Investigate relationships between seasonal conditions and agricultural outcomes.
 Compare relevant groups within different seasons.
 Identify significant differences or unusual patterns.
 Apply appropriate statistical and visualization techniques.
 Interpret findings based on evidence from the dataset.
 Develop meaningful conclusions and data-driven recommendations.
"""

# ---------------------------------------------------------
# CELL 1: IMPORT REQUIRED LIBRARIES
# ---------------------------------------------------------

# Pandas is used for data loading, cleaning and analysis
import pandas as pd

# NumPy is used for numerical calculations
import numpy as np

# Matplotlib is used for creating visualizations
import matplotlib.pyplot as plt

# Seaborn is used for attractive statistical visualizations
import seaborn as sns

# This allows us to upload files directly into Google Colab
from google.colab import files

# Set the overall visualization style
sns.set_theme(style="whitegrid")

# Set the default size of our graphs
plt.rcParams["figure.figsize"] = (10, 6)

# Set the default font sizes
plt.rcParams["axes.titlesize"] = 16
plt.rcParams["axes.labelsize"] = 12

print("All libraries imported successfully!")

# ---------------------------------------------------------
# CELL 2: UPLOAD AND LOAD THE DATASET
# ---------------------------------------------------------

# Upload the CSV file from your computer
uploaded = files.upload()

# Find the uploaded CSV file
file_name = next(
    name for name in uploaded
    if name.lower().endswith(".csv")
)

# Read the CSV file using Pandas
df = pd.read_csv(file_name)

# Display a confirmation message
print("Dataset loaded successfully!")

# Display the name of the file
print("File Name:", file_name)

# ---------------------------------------------------------
# CELL 3: DISPLAY THE DATASET
# ---------------------------------------------------------

# Display the number of rows and columns
print("Dataset Shape:", df.shape)

# Display the first 5 records
print("\nFirst 5 Records:")
display(df.head())

# ---------------------------------------------------------
# CELL 4: DISPLAY LAST 5 RECORDS
# ---------------------------------------------------------

# Display the last 5 rows of the dataset
print("Last 5 Records:")

display(df.tail())

# ---------------------------------------------------------
# CELL 5: DISPLAY COLUMN NAMES
# ---------------------------------------------------------

# Print all column names with their serial numbers

print("Columns in the Dataset:\n")

for number, column in enumerate(df.columns, 1):
    print(number, ".", column)

# ---------------------------------------------------------
# CELL 6: DATASET INFORMATION
# ---------------------------------------------------------

# Display information about:
# - Number of records
# - Column names
# - Data types
# - Non-null values

print("Dataset Information:\n")

df.info()

# ---------------------------------------------------------
# CELL 7: CHECK FOR MISSING VALUES
# ---------------------------------------------------------

# Count missing values in every column
missing_values = df.isnull().sum()

# Display only columns that contain missing values
print("Columns containing missing values:")

display(
    missing_values[missing_values > 0]
)

# ---------------------------------------------------------
# CELL 8: CHECK FOR DUPLICATE RECORDS
# ---------------------------------------------------------

# Count the number of completely duplicated rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

# ---------------------------------------------------------
# CELL 9: DATA CLEANING
# ---------------------------------------------------------

# Create a copy so that the original dataset remains unchanged
df_clean = df.copy()

# ---------------------------------------------------------
# HANDLE NUMERICAL MISSING VALUES
# ---------------------------------------------------------

# Select all numerical columns
numeric_columns = df_clean.select_dtypes(
    include=np.number
).columns

# Replace missing numerical values with the median
# Median is useful because it is less affected by extreme values
for column in numeric_columns:

    df_clean[column] = df_clean[column].fillna(
        df_clean[column].median()
    )


# ---------------------------------------------------------
# HANDLE CATEGORICAL MISSING VALUES
# ---------------------------------------------------------

# Select all categorical/text columns
categorical_columns = df_clean.select_dtypes(
    include="object"
).columns

# Replace missing categorical values with the most common value
for column in categorical_columns:

    if df_clean[column].isnull().sum() > 0:

        df_clean[column] = df_clean[column].fillna(
            df_clean[column].mode()[0]
        )


# ---------------------------------------------------------
# CHECK CLEANED DATASET
# ---------------------------------------------------------

print("Data cleaning completed successfully!")

print(
    "Remaining missing values:",
    df_clean.isnull().sum().sum()
)

# ---------------------------------------------------------
# CELL 10: DESCRIPTIVE STATISTICS
# ---------------------------------------------------------

# Generate statistical summary for numerical columns
# This includes:
# count, mean, standard deviation,
# minimum, maximum and quartiles

statistics = df_clean.describe()

# Display the statistical summary
display(statistics)

# ---------------------------------------------------------
# CELL 11: NUMBER OF RECORDS BY SEASON
# ---------------------------------------------------------

# Count the number of records belonging to each season
season_counts = df_clean["Season"].value_counts()

# Display the result
print("Number of Records by Season:")
display(season_counts)

# ---------------------------------------------------------
# CELL 12: VISUALIZATION 1
# AVERAGE YIELD BY SEASON
# ---------------------------------------------------------

# Define the correct seasonal order
season_order = ["Kharif", "Rabi", "Zaid"]

# Calculate average yield for each season
season_yield = (
    df_clean
    .groupby("Season")["Yield_Tonnes_Ha"]
    .mean()
    .reindex(season_order)
)

# Create the bar chart
plt.figure(figsize=(10, 6))

ax = sns.barplot(
    x=season_yield.index,
    y=season_yield.values
)

# Add chart title
plt.title(
    "Average Agricultural Yield by Season",
    fontweight="bold"
)

# Add axis labels
plt.xlabel("Season")
plt.ylabel("Average Yield (Tonnes/Ha)")

# Display values on top of each bar
for i, value in enumerate(season_yield.values):

    ax.text(
        i,
        value + 0.1,
        f"{value:.2f}",
        ha="center",
        fontweight="bold"
    )

# Adjust the layout
plt.tight_layout()

# Display the graph
plt.show()

# ---------------------------------------------------------
# CELL 13: VISUALIZATION 2
# AVERAGE PROFIT BY SEASON
# ---------------------------------------------------------

# Calculate the average profit for each season
season_profit = (
    df_clean
    .groupby("Season")["Profit_INR"]
    .mean()
    .reindex(season_order)
)

# Create the bar chart
plt.figure(figsize=(10, 6))

ax = sns.barplot(
    x=season_profit.index,
    y=season_profit.values
)

# Add title
plt.title(
    "Average Profit by Agricultural Season",
    fontweight="bold"
)

# Add axis labels
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")

# Display profit values above bars
for i, value in enumerate(season_profit.values):

    # Choose a small offset depending on positive/negative value
    offset = 5000 if value >= 0 else -15000

    ax.text(
        i,
        value + offset,
        f"₹{value:,.0f}",
        ha="center",
        fontweight="bold"
    )

# Keep the actual INR values visible
plt.ticklabel_format(
    style="plain",
    axis="y"
)

# Adjust layout
plt.tight_layout()

# Display graph
plt.show()

# ---------------------------------------------------------
# CELL 14: VISUALIZATION 3
# AVERAGE YIELD BY CROP
# ---------------------------------------------------------

# Calculate average yield for every crop
crop_yield = (
    df_clean
    .groupby("Crop")["Yield_Tonnes_Ha"]
    .mean()
    .sort_values(ascending=True)
)

# Create horizontal bar chart
plt.figure(figsize=(10, 7))

ax = sns.barplot(
    x=crop_yield.values,
    y=crop_yield.index
)

# Add title
plt.title(
    "Average Yield by Crop",
    fontweight="bold"
)

# Add axis labels
plt.xlabel("Average Yield (Tonnes/Ha)")
plt.ylabel("Crop")

# Display values at the end of each bar
for i, value in enumerate(crop_yield.values):

    ax.text(
        value + 0.5,
        i,
        f"{value:.2f}",
        va="center",
        fontweight="bold"
    )

# Adjust layout
plt.tight_layout()

# Display graph
plt.show()

# ---------------------------------------------------------
# CELL 15: VISUALIZATION 4
# WATER-USE EFFICIENCY BY IRRIGATION METHOD
# ---------------------------------------------------------

# Calculate average water efficiency for each irrigation method
water_efficiency = (
    df_clean
    .groupby("Irrigation_Method")
    ["Water_Efficiency_t_per_1000m3"]
    .mean()
    .sort_values(ascending=False)
)

# Create the bar chart
plt.figure(figsize=(10, 6))

ax = sns.barplot(
    x=water_efficiency.index,
    y=water_efficiency.values
)

# Add title
plt.title(
    "Average Water-Use Efficiency by Irrigation Method",
    fontweight="bold"
)

# Add axis labels
plt.xlabel("Irrigation Method")

plt.ylabel(
    "Tonnes per 1,000 m³ of Water"
)

# Display values above the bars
for i, value in enumerate(water_efficiency.values):

    ax.text(
        i,
        value + 0.15,
        f"{value:.2f}",
        ha="center",
        fontweight="bold"
    )

# Adjust layout
plt.tight_layout()

# Display graph
plt.show()

# ---------------------------------------------------------
# CELL 16: VISUALIZATION 5
# RAINFALL VS AGRICULTURAL YIELD
# ---------------------------------------------------------

# Create the figure
plt.figure(figsize=(10, 6))

# Create scatter plot
# Each point represents an agricultural observation
# Different colors represent different seasons
sns.scatterplot(
    data=df_clean,
    x="Rainfall_mm",
    y="Yield_Tonnes_Ha",
    hue="Season",
    alpha=0.65
)

# Add a trend line
# This helps us understand the overall linear relationship
sns.regplot(
    data=df_clean,
    x="Rainfall_mm",
    y="Yield_Tonnes_Ha",
    scatter=False,
    color="black",
    line_kws={"linewidth": 2}
)

# Add title
plt.title(
    "Rainfall vs Agricultural Yield",
    fontweight="bold"
)

# Add axis labels
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (Tonnes/Ha)")

# Add legend
plt.legend(title="Season")

# Adjust layout
plt.tight_layout()

# Display graph
plt.show()


# ---------------------------------------------------------
# CALCULATE CORRELATION
# ---------------------------------------------------------

# Calculate Pearson correlation between rainfall and yield
correlation = df_clean[
    "Rainfall_mm"
].corr(
    df_clean["Yield_Tonnes_Ha"]
)

# Display correlation
print(
    "Pearson Correlation between Rainfall and Yield:",
    round(correlation, 3)
)

# ---------------------------------------------------------
# CELL 17: CORRELATION HEATMAP
# ---------------------------------------------------------

# Select only numerical columns
numeric_data = df_clean.select_dtypes(
    include=np.number
)

# Calculate correlation between numerical variables
correlation_matrix = numeric_data.corr()

# Create heatmap
plt.figure(figsize=(16, 12))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0
)

# Add title
plt.title(
    "Correlation Heatmap of Agricultural Variables",
    fontweight="bold"
)

# Adjust layout
plt.tight_layout()

# Display heatmap
plt.show()

# ---------------------------------------------------------
# CELL 18: SEASONAL PERFORMANCE SUMMARY
# ---------------------------------------------------------

# Calculate important agricultural indicators
# for each season

season_summary = df_clean.groupby("Season").agg({

    # Average yield
    "Yield_Tonnes_Ha": "mean",

    # Average production
    "Production_Tonnes": "mean",

    # Average profit
    "Profit_INR": "mean",

    # Average water usage
    "Water_Used_m3": "mean",

    # Average water efficiency
    "Water_Efficiency_t_per_1000m3": "mean",

    # Average disease and pest risk
    "Disease_Pest_Risk_pct": "mean"

}).round(2)

# Display the summary table
display(season_summary)

# ---------------------------------------------------------
# CELL 19: TOP 5 CROPS BY AVERAGE YIELD
# ---------------------------------------------------------

# Calculate average yield for each crop
top_crops = (
    df_clean
    .groupby("Crop")["Yield_Tonnes_Ha"]
    .mean()
    .sort_values(ascending=False)
    .head(5)
)

# Display the top 5 crops
print("Top 5 Crops by Average Yield:")

display(top_crops)

"""# Key Insights

1. Kharif records the highest average agricultural yield among the three seasons.

2. Kharif also demonstrates the strongest average profit in the dataset.

3. Zaid records negative average profit, indicating weaker economic performance.

4. Sugarcane has a substantially higher average yield compared with the other crops.

5. Pulses records the lowest average yield among the analyzed crops.

6. Rainfed irrigation shows the highest average water-use efficiency in the dataset.

7. Flood irrigation shows the lowest average water-use efficiency.

8. Rainfall has a very weak linear relationship with agricultural yield, with a Pearson correlation of approximately 0.031.

9. Agricultural performance cannot be explained by a single factor such as rainfall.

10. Crop type, irrigation, soil conditions, farming practices and economic factors should be considered together when evaluating agricultural performance.

# Recommendations

1. Agricultural planning should consider seasonal differences in productivity.

2. The factors contributing to stronger Kharif performance should be investigated further.

3. Crop selection should consider historical productivity and economic performance.

4. Water-use efficiency should be considered when selecting irrigation practices.

5. Alternative irrigation methods should be evaluated where Flood irrigation shows lower efficiency.

6. Rainfall should not be considered independently when predicting or evaluating agricultural yield.

7. Soil conditions, fertilizer use, irrigation, temperature, humidity and crop characteristics should be analyzed together.

8. The reasons behind negative average profitability during Zaid should be investigated.

# Limitations

1. The analysis is based only on the variables available in the supplied dataset.

2. Correlation does not establish causation.

3. Rainfall alone does not explain agricultural yield.

4. The analysis may not capture every real-world agricultural factor.

5. The results represent patterns observed in this dataset and should not automatically be generalized to all agricultural regions.

# Conclusion

The Seasonal Agriculture Performance Analysis shows that agricultural performance varies across seasons, crops and farming practices.

Kharif demonstrates the strongest average yield and profit among the analyzed seasons. Crop-level analysis shows significant differences in productivity, with Sugarcane having the highest average yield and Pulses having the lowest.

The irrigation analysis shows differences in water-use efficiency across irrigation methods. The rainfall and yield analysis shows only a very weak linear relationship, indicating that agricultural productivity depends on multiple factors rather than rainfall alone.

Overall, the analysis provides useful data-driven insights into seasonal agricultural performance and can support better agricultural planning and resource management.
"""